name: walbzza
description: Sistema gamer ultra clean (Gnome)

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - type: rpm-ostree
    install:
      - steam
      - firefox
      - gnome-tweaks
    remove:
      - gnome-tour
      - gnome-maps
      - gnome-weather
      - gnome-contacts
      - evolution

  - type: default-flatpaks
    system:
      install:
        - com.heroicgameslauncher.hgl
