name: walbzza
description: Sistema gamer ultra clean

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - type: rpm-ostree
    install:
      - steam
      - firefox
      - gnome-tweaks

  - type: default-flatpaks
    system:
      install:
        - com.heroicgameslauncher.hgl
